SELECT
  PERSON_ID,
  CITY,
  STATE,
  CODE_NAME,
  CONTINENT
FROM GLGLIVE.dbo.ADDRESS A
INNER JOIN GLGLIVE.dbo.COUNCIL_MEMBER CM ON A.COUNCIL_MEMBER_ID = CM.COUNCIL_MEMBER_ID
INNER JOIN GLGLIVE.dbo.CODE C ON A.COUNTRY = C.CODE_ID
INNER JOIN GLGLIVE.dbo.CONTINENT_COUNTRY_RELATION CCR ON C.CODE_ID = CCR.CODE_ID
INNER JOIN GLGLIVE.dbo.CONTINENT CC ON CCR.CONTINENT_ID = CC.CONTINENT_ID
