SELECT
  PERSON_ID,
  COUNCIL_MEMBER_ID,
  COALESCE(HIGH_VALUE_IND, 0),
  COALESCE(LEARNING_DEVELOPMENT_IND, 0),
  COALESCE(SHORT_BIO, BIOGRAPHY),
  PHONE,
  MOBILE,
  COALESCE(BIO_SCREEN_PASS, 0)
FROM
  GLGLIVE.dbo.COUNCIL_MEMBER
WHERE ACTIVE_IND = 1
