SELECT CM.PERSON_ID
        ,KP.COUNCIL_USER_KNOWLEDGE_PROFILE_ID
        ,COALESCE(PQ.QUESTION_TEXT, ' ')
        ,KP.CREATE_DATE as RESPONSE_DATE
        ,COALESCE(KP.COMMENT,' ') AS COMMENT
FROM GLGLIVE.dbo.COUNCIL_USER_KNOWLEDGE_PROFILE KP
JOIN GLGLIVE.dbo.COUNCIL_MEMBER CM
  ON KP.COUNCIL_USER_ID = CM.COUNCIL_MEMBER_ID
LEFT JOIN GLGLIVE.dbo.PROFILE_QUESTION PQ
  ON  PQ.PROFILE_QUESTION_ID = KP.SOURCE_ID
  AND KP.KNOWLEDGE_PROFILE_SOURCE_TYPE_ID = 13773
WHERE KP.ACTIVE_IND = 1
AND KP.VALUE_TEXT = 'Yes'
AND COMMENT <> ' '
