SELECT
  PERSON_ID,
  c.CONSULTATION_ID,
  TITLE,
  CONSULTATION_DESCRIPTION_TEXT,
  GIVE_TO_CLIENT_DATE
FROM
  GLGLIVE.consult.CONSULTATION c
  INNER JOIN GLGLIVE.consult.CONSULTATION_PARTICIPANT cp on c.CONSULTATION_ID = cp.CONSULTATION_ID
WHERE
  c.ACTIVE_IND = 1
  AND cp.ACTIVE_IND = 1
  AND GIVE_TO_CLIENT_DATE IS NOT NULL
