SELECT
  cm.PERSON_ID,
  ut.PERSON_ID
FROM
  GLGLIVE.dbo.COUNCIL_LEAD cl
  INNER JOIN GLGLIVE.dbo.COUNCIL_MEMBER cm ON cm.COUNCIL_MEMBER_ID = cl.COUNCIL_MEMBER_ID
  INNER JOIN GLGLIVE.dbo.USER_TABLE ut ON ut.USER_ID = RECRUITER_ID
