
--no kidding, delete the semicolon and it will not run with bcp
;
WITH AVERAGE_RATES
AS
(
SELECT
  A.COUNTRY,
  CM.PRACTICE_AREA_ID,
  AVG(cmr.RATE_AMOUNT) RATE
FROM GLGLIVE.dbo.ADDRESS A
INNER JOIN GLGLIVE.dbo.COUNCIL_MEMBER CM ON A.COUNCIL_MEMBER_ID = CM.COUNCIL_MEMBER_ID
INNER JOIN GLGLIVE.dbo.COUNCIL_MEMBER_RATE CMR ON CM.COUNCIL_MEMBER_ID = CMR.COUNCIL_MEMBER_ID
WHERE
  CMR.ACTIVE_IND = 1
  AND CMR.CURRENT_IND = 1
  AND CMR.PRODUCT_TYPE_ID = 3
  AND CMR.COUNCIL_MEMBER_ID > 0
  AND A.COUNTRY > 0
GROUP BY
 A.COUNTRY,
 CM.PRACTICE_AREA_ID
)
SELECT
  PERSON_ID,
  RATE
FROM GLGLIVE.dbo.ADDRESS A
INNER JOIN GLGLIVE.dbo.COUNCIL_MEMBER CM ON A.COUNCIL_MEMBER_ID = CM.COUNCIL_MEMBER_ID
INNER JOIN AVERAGE_RATES AR ON AR.COUNTRY = A.COUNTRY AND AR.PRACTICE_AREA_ID = CM.PRACTICE_AREA_ID
