SELECT
  PERSON_ID,
  CR.COUNCIL_MEMBER_FLAG_ID,
  CMF.FLAG_NAME,
  CR.COMMENTS
FROM
  GLGLIVE.dbo.COUNCIL_MEMBER CM
  INNER JOIN GLGLIVE.dbo.COUNCIL_MEMBER_FLAG_RELATION CR ON CM.COUNCIL_MEMBER_ID = CR.COUNCIL_MEMBER_ID
  INNER JOIN GLGLIVE.dbo.COUNCIL_MEMBER_FLAG CMF ON CMF.COUNCIL_MEMBER_FLAG_ID = CR.COUNCIL_MEMBER_FLAG_ID
WHERE CR.ACTIVE_IND = 1
AND CM.ACTIVE_IND = 1