SELECT
  cp.PERSON_ID
  ,c.CONSULTATION_ID
  ,c.TITLE
  ,CONSULTATION_DESCRIPTION_TEXT
  ,p.LAST_NAME
  ,p.FIRST_NAME
  ,GIVE_TO_CLIENT_DATE
FROM
  GLGLIVE.consult.CONSULTATION c
  INNER JOIN GLGLIVE.consult.CONSULTATION_PARTICIPANT cp on c.CONSULTATION_ID = cp.CONSULTATION_ID
  INNER JOIN GLGLIVE.dbo.PERSON p on p.PERSON_ID = c.PRIMARY_RM_PERSON_ID
WHERE
  c.ACTIVE_IND = 1
  AND cp.ACTIVE_IND = 1
  AND GIVE_TO_CLIENT_DATE IS NOT NULL
  AND p.LAST_NAME != ''
  AND p.FIRST_NAME != ''
ORDER BY
  cp.PERSON_ID
