SELECT
  cp.PERSON_ID
  ,p.PERSON_ID
  ,p.LAST_NAME
  ,p.FIRST_NAME
  ,count(1)
FROM
  GLGLIVE.consult.CONSULTATION c
  INNER JOIN GLGLIVE.consult.CONSULTATION_PARTICIPANT cp on c.CONSULTATION_ID = cp.CONSULTATION_ID
  INNER JOIN GLGLIVE.dbo.PERSON p on p.PERSON_ID = c.PRIMARY_RM_PERSON_ID
WHERE
  c.ACTIVE_IND = 1
  AND cp.ACTIVE_IND = 1
  AND GIVE_TO_CLIENT_DATE IS NOT NULL
  AND p.LAST_NAME != ''
  AND p.FIRST_NAME != ''
group by cp.PERSON_ID, p.person_ID, p.LAST_NAME, p.FIRST_NAME
order by cp.PERSON_ID
