#!/usr/bin/env bash

#and run the first parameter as the query
QUERY="${1}"

export TDSVER="7.1"
freebcp "$(cat ${QUERY})" queryout /dev/stdout -S "${GLGLIVE}" -U "${GLGLIVE_USER}" -P "${GLGLIVE_PWD}" -c -r "\r\t" -t "\t" -O "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED"
