#!/usr/bin/env gawk -f
@include "transforms/records";

BEGIN {
  #zero out the counters
  print "db.people.update("
  print "{},"
  print "{ $set: {numProjectsPaid: 0} },"
  print "{ upsert: true, multi: true }"
  print ");\n"
}

{
  escape();
  print "db.people.update("
  printf "{ personid: '%s'},\n", $1
  printf "{ $inc: {numProjectsPaid: 1} },\n"
  printf "{ upsert: true }\n"
  print ");\n"
}
