#!/usr/bin/env gawk -f
@include "transforms/records";

{
  escape();
  print "db.people.update("
  printf "{ personid: '%s'},\n", $1
  printf "{ $set: {city: '%s', state: '%s', country: '%s', continent: '%s'} },\n", $2, $3, $4, $5
  printf "{ upsert: true }\n"
  print "\n);\n"

  #N/A default values, always make up a full path, this will let the facets have counts
  #of otherwise unclassified folks
  geographyFacets[1] = defaultValue($5, "N/A");
  geographyFacets[2] = defaultValue($4, "N/A");
  geographyFacets[3] = defaultValue($3, "N/A");
  geographyFacets[4] = defaultValue($2, "N/A");
  print geographyFacets[1]
  facetize($1, geographyFacets, "geo_taxonomy_Facet");

}
