#!/usr/bin/env gawk -f
@include "transforms/records";

"hourly" {
  escape();
  print "db.people.update("
  printf "{ hashkey: 'person-%s'}, ", $1
  printf "{ $set: {benchmarkRate: %s} },\n", $2
  printf "{ upsert: true }\n"
  print ");\n"
}
