#!/usr/bin/env gawk -f
@include "transforms/records";

#all jobs
{
  escape();
  startDate = employmentDate($5, $6)
  endDate = employmentDate($7, $8)
  #just the job itself
  print "db.people.update("
  printf "{personid: '%s'},\n", $1
  printf "{$set: {'jobs.%s': {nameOfCompany: '%s', jobTitle: '%s', startDate: '%s', endDate: '%s', isCurrent: %i, TaxonomySector: '%s'} } },\n", $2, $3, $4, startDate, endDate, $9, $10
  printf "{upsert: true }\n"
  print ");"

  #separate taxonomy sets
  print "db.people.update("
  printf "{ personid: '%s'},\n", $1
  printf "{ $addToSet: {taxonomySector: '%s'} },\n", $10
  printf "{ upsert: true }\n"
  print ");\n"
  facetize($1, $10, "taxonomySector_All_Facet")
  facetize($1, $11, "taxonomyJobFunction_All_Facet")
}

#current jobs
$9 == "1" {
  facetize($1, $10, "taxonomySector_AllCurrent_Facet")
  facetize($1, $11, "taxonomyJobFunction_AllCurrentt_Facet")
}
