#!/usr/bin/env gawk -f
@include "transforms/records";

function closeperson() {
  //closing out the last record
  if (NR > 1) {
    print "}}},";
    print "{ upsert: true }";
    print ");\n";
    print "//BATCH";
  }
}

BEGIN {
  person="";
}

person != $1 {
  closeperson();
  person=$1;
  print "db.people.update("
  printf "{ hashkey: 'person-%s'},\n", $1;
  print "{ $set: {profileQuestions: {";
}

{
  escape();
  printf "'%s':{ QuestionText: '%s', ResponseDate: '%s', ResponseText: '%s'},\n", $2, $3, $4, $5
}

END {
  closeperson();
}
