#!/usr/bin/env gawk -f
@include "transforms/records";

{
escape();
#just the flag itself
print "db.people.update("
printf "{ personid: '%s'},\n", $1
printf "{ $set: {'flags.%s': {councilMemberFlagId: %d, flagName: '%s', comments: '%s'} } },\n", $2, $2, $3, $4
printf "{ upsert: true }\n"
print "\n);\n"
}

#all the magical DNC codes
function DNC(flag) {
  print "//DNC for " flag
  print "db.people.update("
  printf "{ personid: '%s'},\n", $1
  printf "{ $set: {isDNC: true} },\n"
  printf "{ upsert: true }\n"
  print "\n);\n"
}
$2 == "1" {
  DNC($2);
}
$2 == "2" {
  DNC($2);
}
$2 == "3" {
  DNC($2);
}
$2 == "4" {
  DNC($2);
}
$2 == "13733" {
  DNC($2);
}
$2 == "13734" {
  DNC($2);
}

$2 == "24" {
  print "db.people.update("
  printf "{ personid: '%s'},\n", $1
  printf "{ $set: {isFirstAccess: true} },\n"
  printf "{ upsert: true }\n"
  print "\n);\n"
}

$2 == "43" {
print "db.people.update("
printf "{ personid: '%s'},\n", $1
printf "{ $set: {isKeyExecutive: true} },\n"
printf "{ upsert: true }\n"
print "\n);\n"
}

$2 == "19" || $2 == "20" || $2 == "21" {
print "db.people.update("
printf "{ personid: '%s'},\n", $1
printf "{ $set: {isMemberPrograms: true} },\n"
printf "{ upsert: true }\n"
print "\n);\n"
}
