#!/usr/bin/env gawk -f
@include "transforms/records";

#batch separators every N records, just a comment marker
#this is used as a split point piping along to parallel
NR%100==0 {
  print "//BATCH";
}


#all jobs
{
  escape();
}

$2 < 365 {
  print "db.people.update("
  printf "{ hashkey: 'person-%s'}, ", $1
  printf "{ $set: {recentContact: true} },\n", $3
  printf "{ upsert: true }\n"
  print ");\n"
}
