#!/usr/bin/env gawk -f
@include "transforms/records";

$2 == "hourly" {
escape();
print "db.people.update("
printf "{ hashkey: 'person-%s'}, ", $1
printf "{ $set: {hourlyRate: %s} },\n", $3
printf "{ upsert: true }\n"
print ");\n"
}

$2 == "expert" {
escape();
print "db.people.update("
printf "{ hashkey: 'person-%s'}, ", $1
printf "{ $set: {expertWitnessRate: %s} },\n", $3
printf "{ upsert: true }\n"
print ");\n"
}
