#!/usr/bin/env gawk -f
@include "transforms/records";

{
escape();
print "db.people.update("
printf "{ hashkey: 'person-%s'}, ", $1
printf "{ $set: {recruitedBy: %i} },\n", $2
printf "{ upsert: true }\n"
print "\n);\n"
}
