#!/usr/bin/env gawk -f
@include "transforms/records";

{
escape();
print "db.people.update("
printf "{ personid: %i},\n", $1
printf "{ $set: {type: 'councilmember', councilmemberid: %i, isHighValue: %i, isLearning: %i, biography: '%s', phone: '%s', mobile: '%s', isDNC: false} },\n", $2, $3, $4, $5, $6, $7
printf "{ upsert: true }\n"
print "\n);\n"
}
