#!/usr/bin/env gawk -f
@include "transforms/records";

#batch separators every N records, just a comment marker
#this is used as a split point piping along to parallel
NR%100==0 {
  print "//BATCH";
}


{
  escape();
  print "db.people.update("
  printf "{ hashkey: 'person-%s'}, ", $1
  printf "{ $set: {practicearea: '%s'} },", $2
  print "{ upsert: true, multi: true }"
  print ");\n"
}
