#!/usr/bin/env gawk -f
@include "transforms/records";

{
  escape();
  print "db.people.update("
  printf "{ personid: %i},\n", $1
  printf "{ $set: {numProjectsPaid: %s} },", $2
  print "{ upsert: true, multi: true }"
  print ");\n"
}
