#!/usr/bin/env gawk -f
@include "transforms/records";

{
  escape();
  print "db.people.update("
  print "{},"
  print "{ $set: {numProjectsPaid: $2} },"
  print "{ upsert: true, multi: true }"
  print ");\n"
}
