#!/usr/bin/env gawk -f
@include "transforms/records";

{
escape();
print "db.people.update("
printf "{ personid: %i},\n", $1
printf "{ $set: {recruitedBy: %i} },\n", $2
printf "{ upsert: true }\n"
print "\n);\n"
}
