#!/usr/bin/env gawk -f
@include "transforms/records";

#all jobs
{
  escape();
  startDate = employmentDate($6, $7)
  endDate = employmentDate($8, $9)
  #just the job itself
  print "db.people.update("
  printf "{ hashkey: 'person-%s'}, ", $1
  printf "{$set: {'jobs.%s': {nameOfCompany: '%s', companyId: '%s', jobTitle: '%s', startDate: '%s', endDate: '%s', isCurrent: %i, TaxonomySector: '%s'} } },\n", $2, $3, $4, $5, startDate, endDate, $10, $11
  printf "{upsert: true }\n"
  print ");"

  if ($11) {
    #separate taxonomy sets
    print "db.people.update("
    printf "{ hashkey: 'person-%s'}, ", $1
    printf "{ $addToSet: {taxonomySector: '%s'} },\n", $11
    printf "{ upsert: true }\n"
    print ");\n"
  }
  if (length($11))
    facetize($1, $11, "taxonomySector_All_Facet")
  if (length($12))
    facetize($1, $12, "taxonomyJobFunction_All_Facet")

  print "db.people.update("
  printf "{ hashkey: 'person-%s'}, ", $1
  printf "{ $addToSet: {company_All_Bucket: '%s'} },\n", $3
  printf "{ upsert: true }\n"
  print ");\n"
}

#current jobs
$10 == "1" {
  if (length($11))
    facetize($1, $11, "taxonomySector_AllCurrent_Facet")
  if (length($12))
    facetize($1, $12, "taxonomyJobFunction_AllCurrent_Facet")


  print "db.people.update("
  printf "{ hashkey: 'person-%s'}, ", $1
  printf "{ $addToSet: {company_AllCurrent_Bucket: '%s'} },\n", $3
  printf "{ upsert: true }\n"
  print ");\n"
}

#former jobs
$10 == "0" {
  if (length($11))
    facetize($1, $11, "taxonomySector_AllFormer")
  if (length($12))
    facetize($1, $12, "taxonomyJobFunction_AllFormer_Facet")


  print "db.people.update("
  printf "{ hashkey: 'person-%s'}, ", $1
  printf "{ $addToSet: {company_AllFormer_Bucket: '%s'} },\n", $3
  printf "{ upsert: true }\n"
  print ");\n"
}
