#!/usr/bin/env gawk -f
@include "transforms/records";

function closeperson() {
  //closing out the last record
  if (NR > 1) {
    print "]}},";
    print "{ upsert: true }";
    print ");\n";
    print "//BATCH";
  }
}

BEGIN {
  person="";
}

person != $1 {
  closeperson();
  person=$1;
  print "db.people.update("
  printf "{ hashkey: 'person-%s'},\n", $1;
  print "{ $set: {projectHistory: [";
  first=true;
}

{
  escape();
  if (first) {
    first=false;
  } else {
    printf ",";
  }
  printf "{title: '%s', description: '%s', rm: {lastName: '%s', firstName: '%s'}, date: '%s'}\n", $3, $4, $5, $6, $7
}

END {
  closeperson();
}
