#!/usr/bin/env gawk -f
@include "transforms/records";

#batch separators every N records, just a comment marker
#this is used as a split point piping along to parallel
NR%100==0 {
  print "//BATCH";
}


$2 == "hourly" {
escape();
print "db.people.update("
printf "{ hashkey: 'person-%s'}, ", $1
printf "{ $set: {hourlyRate: %s} },\n", $3
printf "{ upsert: true }\n"
print ");\n"
}

$2 == "expert" {
escape();
print "db.people.update("
printf "{ hashkey: 'person-%s'}, ", $1
printf "{ $set: {expertWitnessRate: %s} },\n", $3
printf "{ upsert: true }\n"
print ");\n"
}
