#!/usr/bin/env gawk -f
@include "transforms/records";

#batch separators every N records, just a comment marker
#this is used as a split point piping along to parallel
NR%100==0 {
  print "//BATCH";
}


#all jobs
{
  escape();
  startDate = employmentDate($6, $7)
  endDate = employmentDate($8, $9)
  #just the job itself
  print "db.people.update("
  printf "{ hashkey: 'lead-%s'}, ", $1
  printf "{$set: {'jobs.%s': {nameOfCompany: '%s', companyId: '%s', jobTitle: '%s', startDate: '%s', endDate: '%s', isCurrent: %i} } },\n", $2, $3, $4, $5, startDate, endDate, $10
  printf "{upsert: true }\n"
  print ");"
}
