#!/usr/bin/env gawk -f
@include "transforms/records";

BEGIN {
  print "db.people.ensureIndex({leadid: 1});";
}

{
  escape();
  print "db.people.update("
  printf "{ leadid: %i}, ", $1
  printf "{ $set: {hashkey: 'lead-%s', type: 'lead', leadid: %i, name: '%s', firstname: '%s', lastname: '%s', email: '%s', biography: '%s'} },\n", $1, $1, $2, $3, $4, $5, $6
  printf "{ upsert: true }\n"
  print ");\n"
}
