#!/usr/bin/env gawk -f
@include "transforms/records";

#batch separators every N records, just a comment marker
#this is used as a split point piping along to parallel
NR%100==0 {
  print "//BATCH";
}


BEGIN {
  print "db.people.ensureIndex({leadid: 1});";
  print "db.people.ensureIndex({hashkey: 1});";
}

{
  escape();
  print "db.people.update("
  printf "{ hashkey: 'lead-%s'}, ", $1
  printf "{ $set: {hashkey: 'lead-%s', type: 'lead', leadid: %i, name: '%s', firstname: '%s', lastname: '%s', email: '%s', biography: '%s'} },\n", $1, $1, $2, $3, $4, $5, $6
  printf "{ upsert: true }\n"
  print ");\n"
}
