#!/usr/bin/env gawk -f
@include "transforms/records";

#batch separators every N records, just a comment marker
#this is used as a split point piping along to parallel
NR%100==0 {
  print "//BATCH";
}

{
  escape();
  print "db.people.update("
  printf "{ hashkey: 'person-%s'}, ", $1
  printf "{ $set: {hashkey: 'person-%s', personid: %i, name: '%s', firstname: '%s', lastname: '%s', email: '%s'} },\n", $1, $1, $2, $3, $4, $5
  printf "{ upsert: true }\n"
  print ");\n"
}
